---
name: CI

on: [push, pull_request]

jobs:
  test:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        shell: bash
        run: |
          pip install pytest flake8 black fsspec
          pip install setuptools wheel twine
          pip install fsspec
      - name: Install Rclone
        shell: bash
        run: |
          wget -nv https://downloads.rclone.org/rclone-current-linux-amd64.deb
          sudo dpkg -i rclone-current-linux-amd64.deb
      - name: Run tests
        shell: bash
        run: pytest -v fsspec_rclone
      - name: Lint
        shell: bash
        run: |
          flake8 fsspec_rclone
          black fsspec_rclone --check
      - name: Build package
        shell: bash
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish package
        if: startsWith(github.ref, 'refs/tags/v') && matrix.python-version == '3.7'
        shell: bash
        run: |
          twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
...
